In [364]:
import pandas as pd
import numpy as np
df= pd.read_csv('HIV smalldata.csv')
df

                                                 SMILES  ACTIVITY
0          C1[C@H]2[C@@H]([C@@H](S1)CCCCC(=O)O)NC(=O)N2         1
1     C1=COC(=C1)/C=C/C=C\2/C(=O)N(C(=S)S2)C(CC(=O)O...         1
2     C1=CC2=C(C(=C1)C3=C4C=CC(=O)C(=C4OC5=C3C=CC(=C...         1
3                     C1=CC(=C(C=C1C[C@@H](C(=O)O)N)O)O         1
4         C1C2=CC(=C(C=C2C3=C4C=CC(=O)C(=C4OCC31O)O)O)O         1
...                                                 ...       ...
2015  C1COCCN1C2=CC=C(C=C2)NCC3=CC4=C(C=C3)OCO4.C(=O...         0
2016          C1=C(C=C(C(=C1/C=N/NC2=NN=CN2N)O)Br)Br.Cl         0
2017  C[C@H]1CN(C(=O)CCCN2C(=CN=N2)CO[C@@H]1CN(C)S(=...         0
2018              CCCCCOC(=O)CC(C(=O)OCCCCC)N1CCCCC1.Cl         0
2019  C[C@]12[C@@H]3[C@H]([C@H](N1C(=O)CN(C2=O)CC4=C...         0

[2020 rows x 2 columns]

In [365]:
from rdkit import Chem
from rdkit.Chem import AllChem
from rdkit.Chem import rdMolDescriptors
from rdkit import DataStructs
import numpy as np
import pandas as pd

In [366]:
smiles_list = df['SMILES'].tolist() 
mols = [Chem.MolFromSmiles(smi) for smi in smiles_list if smi is not None]

In [367]:
def morgan_fps(data):
  fps = [AllChem.GetMorganFingerprintAsBitVect(mol, radius=2, nBits=2048) for mol in data]  # Calculate Morgan fingerprints for each molecule
  fp_array = [np.array(fp) for fp in fps]   # Convert fingerprints to numpy array
  column_names = ["morgan_" + str(i) for i in range(len(fp_array[0]))]
  return pd.DataFrame(fp_array, columns = column_names)

In [368]:
d1 = morgan_fps(mols)
X = pd.concat([d1], axis = 1)
X

,morgan_0,morgan_1,morgan_2,morgan_3,morgan_4,morgan_5,morgan_6,morgan_7,morgan_8,morgan_9,...,morgan_2038,morgan_2039,morgan_2040,morgan_2041,morgan_2042,morgan_2043,morgan_2044,morgan_2045,morgan_2046,morgan_2047
0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,0,1,0,0,0,0,0,0,0,0,...,0,1,0,0,0,0,1,0,0,0
2,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,0,1,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2015,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2016,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,1,0,0,0
2017,0,1,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2018,0,1,1,0,0,0,0,0,0,0,...,0,1,0,0,0,0,0,0,0,0
2019,0,0,0,0,0,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [369]:
X

,morgan_0,morgan_1,morgan_2,morgan_3,morgan_4,morgan_5,morgan_6,morgan_7,morgan_8,morgan_9,...,morgan_2038,morgan_2039,morgan_2040,morgan_2041,morgan_2042,morgan_2043,morgan_2044,morgan_2045,morgan_2046,morgan_2047
0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,0,1,0,0,0,0,0,0,0,0,...,0,1,0,0,0,0,1,0,0,0
2,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,0,1,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2015,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2016,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,1,0,0,0
2017,0,1,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2018,0,1,1,0,0,0,0,0,0,0,...,0,1,0,0,0,0,0,0,0,0
2019,0,0,0,0,0,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [370]:
y = df["ACTIVITY"]
y

0       1
1       1
2       1
3       1
4       1
       ..
2015    0
2016    0
2017    0
2018    0
2019    0
Name: ACTIVITY, Length: 2020, dtype: int64

In [371]:
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.3, random_state = 8)

In [372]:
X_train

,morgan_0,morgan_1,morgan_2,morgan_3,morgan_4,morgan_5,morgan_6,morgan_7,morgan_8,morgan_9,...,morgan_2038,morgan_2039,morgan_2040,morgan_2041,morgan_2042,morgan_2043,morgan_2044,morgan_2045,morgan_2046,morgan_2047
1535,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1809,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
849,0,0,0,0,0,1,0,0,0,1,...,0,0,0,0,0,0,0,0,0,0
1104,0,1,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1010,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
986,0,0,0,0,0,0,0,1,0,0,...,0,0,0,0,0,0,0,0,0,0
133,0,1,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
361,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1364,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
451,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [373]:
from imblearn.over_sampling import SMOTE

# assuming X_train and y_train are your training features and labels

smote = SMOTE(sampling_strategy='minority',random_state=2)

X_sm, y_sm = smote.fit_resample(X_train, y_train)
X_train = X_sm
y_train = y_sm

In [374]:
from sklearn.feature_selection import VarianceThreshold
sel = VarianceThreshold(threshold=0)

# Fit and transform the data
sel.fit(X_train)

mask = sel.get_support()
X = X_train[X_train.columns[mask]]

In [375]:
""""import numpy as np
from sklearn import datasets
from scipy.spatial import distance
def in_applicability_domain(X, X_sm, threshold):
    # Calculate the distance from each point in X to its nearest neighbor in X_train
    dist = distance.cdist(X, X_sm, 'euclidean')
    min_dist = np.min(dist, axis=1)
    
    return min_dist < threshold"""

'"import numpy as np\nfrom sklearn import datasets\nfrom scipy.spatial import distance\ndef in_applicability_domain(X, X_sm, threshold):\n    # Calculate the distance from each point in X to its nearest neighbor in X_train\n    dist = distance.cdist(X, X_sm, \'euclidean\')\n    min_dist = np.min(dist, axis=1)\n    \n    return min_dist < threshold'

In [376]:
""""app_domain = in_applicability_domain(X_test, X_sm, threshold=5.0)

print('Applicability domain:', app_domain)"""

'"app_domain = in_applicability_domain(X_test, X_sm, threshold=5.0)\n\nprint(\'Applicability domain:\', app_domain)'

In [377]:
""""inliers = app_domain
X_test_inliers = X_test[inliers]
X_test = X_test_inliers"""

'"inliers = app_domain\nX_test_inliers = X_test[inliers]\nX_test = X_test_inliers'

In [378]:
#X_test

In [379]:
#y_test_inliers = y_test[inliers]
#y_test = y_test_inliers

In [380]:
from sklearn.ensemble import RandomForestClassifier

rfc = RandomForestClassifier(max_features = 5 , n_estimators = 100, random_state=2)
rfc.fit(X_train, y_train)
#rfc.fit(X_train, y_train)

# Make predictions on the testing set
preds = rfc.predict(X_test)
proba = rfc.predict_proba(X_test)

In [384]:
from sklearn.metrics import matthews_corrcoef
from sklearn.metrics import confusion_matrix
from sklearn.metrics import f1_score
from sklearn.metrics import precision_score
from sklearn.metrics import roc_auc_score

tn, fp, fn, tp = confusion_matrix(y_test, preds).ravel()
sensitivity = tp / (tp + fn)
specificity = tn / (tn + fp)
accuracy = (tn + tp) / (tn+tp+fn+fp)
balanced_accuracy = (sensitivity + specificity) / 2
precision = tp / (tp + fp)
f1 = 2 * (precision * sensitivity) / (precision + sensitivity)
roc_auc = roc_auc_score(y_test, proba[:, 1])

print(f"sensitivity: {sensitivity}, specificity: {specificity}, precision: {precision}, f1: {f1} , accuracy: {accuracy}, roc_auc: {roc_auc} \nbalanced_accuracy: {balanced_accuracy}")

sensitivity: 0.6741071428571429, specificity: 0.837696335078534, precision: 0.7089201877934272, f1: 0.6910755148741419 , accuracy: 0.7772277227722773, roc_auc: 0.8492018044128646
balanced_accuracy: 0.7559017389678384